version: 0.2

phases:
  build:
    commands:
      - cd Project2.0
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - Project2.0/target/Project2.0-0.0.1-SNAPSHOT.jar